baseURL: http://amygroshek.com
disablePathToLower: true
languageCode: en-us
title: Amy Groshek
theme: hugo-creative
title: Avocation and Vocation
relativeURLs: true
languageCode: en-us
# Enable comments by entering your Disqus shortname
disqusShortname: "amygroshek"
# Enable Google Analytics by entering your tracking code
googleAnalytics: ""
# The pre can be used to add an icon :before the menu item.
menu:
  main:
      - Name: "home"
        URL: "/"
        Weight: 1
      - Name: "posts"
        Pre: ""
        URL: "/posts/"
        Weight: 2
      - Name: "cv"
        URL: "/cv/"
        Weight: 3
      - Name: "tango"
        URL: "/tango/"
        Weight: 3.5
      - Name: "contact"
        URL: "/contact/"
        Weight: 4
      - Name: "hire"
        Pre: ""
        URL: "http://hire.amygroshek.com"
        Weight: 5
params:
  # Style options: default (pink), blue, green, pink, red, sea, violet
  style: pink
  description: "Avocation and Vocation"
  copyright: "&copy; Amy Groshek 2012 onwards"
  sidebarAbout: [
    "I am a PhD student, sometime poet, freelance web developer, and Argentine tango instructor.",
    "The landing page showcases my electronic poetry projects. Most of my electronic literature uses programming languages and web browsers as formal constraints."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email: "amygroshek@gmail.com"

  social:
  # facebook      = "full page or profile url in facebook"
  #  googleplus    = "full profile url in googleplus"
    email: "amygroshek@gmail.com"
    twitter: "https://twitter.com/amygroshek"
    linkedin: "https://www.linkedin.com/in/amy-groshek-b7a2683/"
    stackoverflow: "https://stackoverflow.com/users/590107/brokenindexfinger"
  # instagram     = "full profile url in instagram"
    github: "https://github.com/amygroshek"
